### PR TITLE
Update for 2018.

### PR DESCRIPTION
**Pull request by PeterJohnson**

### CODE REVIEW

**Comment by PeterJohnson** [comment]
This updates the compiler to 5.4.0 and binutils to 2.28.  The main issue I've seen with the built packages is that it can't upgrade in place as libgcc-4.9-... will not upgrade to libgcc-5.4-... (because the version is part of the package name and the files of the two conflict).  The workaround is to apt remove all of the old 4.9 packages before installing the new 5.4 packages.

**Comment by byteit101** [comment]
`The workaround is to apt remove all of the old 4.9 packages before installing the new 5.4 packages.`
The workaround is to state the "breaks" packages for these cases in the control files

`Conflicts: libgcc-4.9-...`
I can do this this weekend, or you can just add them to this pull request.

**Comment by PeterJohnson** [comment]
I did state libgcc-5.4-xxx `Conflicts: libgcc-4.9-xxx` but this didn't help the upgrade case, as other packages depend on libgcc-4.9-xxx until you uninstall them, apt won't remove libgcc-4.9-xxx to make the libgcc-5.4-xxx upgrade happen.  Unless I'm misunderstanding something?

**Comment by byteit101** [comment]
Oh, I think it also needs to declare "replaces". I should have time to work this out this weekend either way

https://www.debian.org/doc/debian-policy/ch-relationships.html#s-replaces

**Comment by byteit101** [comment]
Weird, I don't seem to have write access. I have merged this locally though with a few small changes, and will push once I do.

**Comment by PeterJohnson** [comment]
Write access to the PR or the repo?

**Comment by ThadHouse** [comment]
The mac readme needs to be updated to say the native gcc needs to be 5.4 `brew install gcc5` instead of 4.9

**Comment by PeterJohnson** [comment]
@byteit101 this has been updated to 5.5.0.  Can you take a look?  Since your fixes weren't here, we probably have conflicts now.

**Comment by PeterJohnson** [comment]
Merged as part of #7.

**Pull request closed without merging**
